### ISSUE TITLE
Forbidden when trying to access survey's uploaded files

### ISSUE THREAD

**Issue by jusabatier** [adamzammit/limesurvey-docker#60]
I defined a survey with a files input, then I test it uploading some photos.

After that when I go to "Resources" menu in survey admin, I see the uploaded files.
But when I try to right click on them and try to View, I get an "Unknown error" in the UI.

In the browser console, I can see that the image URL respond with "Forbidden" : 

URL : https://limesurvey.mydomain.com/upload/surveys/231479/files/fu_ik35n2e6q6k7puf?ts=1729854367790

Response : 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.62 (Debian) Server at mydomain.com Port 80</address>
</body></html>
```

Container log : 

`[access_compat:error] [pid 8242:tid 8242] [client XXX:0] AH01797: client denied by server configuration: /var/www/html/upload/surveys/231479/files/fu_ik35n2e6q6k7puf, referer: https://limesurvey.mydomain.com/vendor/kcfinder/browse.php?language=%27fr%27`

Could it be due to an apache misconfiguration ?

**Comment by adamzammit** [comment]
I can't reproduce that on my copy here (using version 6.6.6)

What version of the container are you using?

Also what volumes do you have configured as it could be a file permission issue?

**Comment by jusabatier** [comment]
Maybe it's due to the helm chart I use : https://github.com/area-42/helm-charts

It uses this image : limesurvey:6.6.6.1
And I just provide 2 PVC (RW) for apache and DB.

**Comment by ChaosKid42** [comment]
I can reproduce it (using the helm chart I authored) but I don't think it's related to the chart. I believe it is due to the [.htaccess](https://github.com/LimeSurvey/LimeSurvey/blob/master/upload/surveys/.htaccess) file in the upload/surveys folder. If you remove it (`rm /var/www/html/upload/surveys/.htaccess`)  viewing will work but everyone will have access to all survey uploads. Might be a feature.

**Comment by ChaosKid42** [comment]
I also reproduced it using purely the container running in podman: Same results.

**Comment by adamzammit** [comment]
apologies I didn't follow your procedure exactly. I can reproduce this behaviour.

I believe this is by design in LimeSurvey to avoid direct access to user uploaded files. All files manually uploaded to resources will be public access, but those uploaded (starting with "fu_") are blocked.

To download the uploaded files, please visit the responses page and select the responses you want to download the files for, then in the "selected responses" dropdown choose: "Download files"

**Comment by jusabatier** [comment]
The reason why I found this behavior is that I searched an URL to use in an automation script that retrieve all responses (and  attached files) to process them.

Edit: Maybe possible via API : https://api.limesurvey.org/classes/remotecontrol-handle.html#method_get_uploaded_files
